# Generated by Django 3.2.4 on 2024-08-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
