# Generated by Django 3.2.4 on 2024-08-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listings_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='duration',
            field=models.IntegerField(help_text='Auction duration in hours'),
        ),
    ]
