# Generated by Django 3.2.4 on 2024-08-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listings_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.user'),
            preserve_default=False,
        ),
    ]
